import Link from 'next/link'
import './globals.css'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='relative'>
        {children}

        <footer className='absolute bottom-2 w-full text-center font-semibold '>Developed by <Link href={'https://www.linkedin.com/feed/?trk=guest_homepage-basic_google-one-tap-submit'} target='_blank' className=' underline'>Alejo Fernandez </Link> </footer>
        </body>
    </html>
  )
}
